<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="imu_length" value="0.05" />
    <xacro:property name="imu_width" value="0.05" />
    <xacro:property name="imu_height" value="0.0025" />

    <link name="base_imu_link">
        <visual>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.025" l="${imu_length}" w="${imu_width}" h="${imu_height}"
                           xyz="0 0 ${imu_height / 2.0}" rpy="0 0 0" />
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_imu_link" />
        <origin xyz="0 0 ${base_height + 0.05 + imu_height/2.0}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="base_imu_link">
        <material>Gazebo/Red</material>
        <sensor name="my_imu" type="imu">
            <always_on>true</always_on>
            <update_rate>200</update_rate>
            <imu>
                <angular_velocity>
                    <x>
                        <noise type="gaussian">
                            <mean>0.0</mean>
                            <stddev>2e-4</stddev>
                        </noise>
                    </x>
                    <y>
                        <noise type="gaussian">
                            <mean>0.0</mean>
                            <stddev>2e-4</stddev>
                        </noise>
                    </y>
                    <z>
                        <noise type="gaussian">
                            <mean>0.0</mean>
                            <stddev>2e-4</stddev>
                        </noise>
                    </z>
                </angular_velocity>
                <linear_acceleration>
                    <x>
                        <noise type="gaussian">
                            <mean>0.0</mean>
                            <stddev>1.7e-2</stddev>
                        </noise>
                    </x>
                    <y>
                        <noise type="gaussian">
                            <mean>0.0</mean>
                            <stddev>1.7e-2</stddev>
                        </noise>
                    </y>
                    <z>
                        <noise type="gaussian">
                            <mean>0.0</mean>
                            <stddev>1.7e-2</stddev>
                        </noise>
                    </z>
                </linear_acceleration>
            </imu>
            <plugin name="my_imu" filename="libgazebo_ros_imu_sensor.so">
                <ros>
                    <!-- <namespace>/tb3</namespace> -->
                    <remapping>~/out:=imu</remapping>
                </ros>
            </plugin>
        </sensor>

    </gazebo>

</robot>